// Code generated by MockGen. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "draftea-challenge/gettransactions/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTransactionsGetter is a mock of TransactionsGetter interface.
type MockTransactionsGetter struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionsGetterMockRecorder
	isgomock struct{}
}

// MockTransactionsGetterMockRecorder is the mock recorder for MockTransactionsGetter.
type MockTransactionsGetterMockRecorder struct {
	mock *MockTransactionsGetter
}

// NewMockTransactionsGetter creates a new mock instance.
func NewMockTransactionsGetter(ctrl *gomock.Controller) *MockTransactionsGetter {
	mock := &MockTransactionsGetter{ctrl: ctrl}
	mock.recorder = &MockTransactionsGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionsGetter) EXPECT() *MockTransactionsGetterMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockTransactionsGetter) Execute(ctx context.Context, userID string) ([]domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, userID)
	ret0, _ := ret[0].([]domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockTransactionsGetterMockRecorder) Execute(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockTransactionsGetter)(nil).Execute), ctx, userID)
}
