// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mocks/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "draftea-challenge/createpayment/internal/domain"
	usecase "draftea-challenge/createpayment/internal/usecase"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentCreator is a mock of PaymentCreator interface.
type MockPaymentCreator struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentCreatorMockRecorder
	isgomock struct{}
}

// MockPaymentCreatorMockRecorder is the mock recorder for MockPaymentCreator.
type MockPaymentCreatorMockRecorder struct {
	mock *MockPaymentCreator
}

// NewMockPaymentCreator creates a new mock instance.
func NewMockPaymentCreator(ctrl *gomock.Controller) *MockPaymentCreator {
	mock := &MockPaymentCreator{ctrl: ctrl}
	mock.recorder = &MockPaymentCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentCreator) EXPECT() *MockPaymentCreatorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockPaymentCreator) Execute(ctx context.Context, input usecase.CreatePaymentInput) (*domain.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*domain.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockPaymentCreatorMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockPaymentCreator)(nil).Execute), ctx, input)
}
