// Code generated by MockGen. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "draftea-challenge/getbalances/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBalanceGetter is a mock of BalanceGetter interface.
type MockBalanceGetter struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceGetterMockRecorder
	isgomock struct{}
}

// MockBalanceGetterMockRecorder is the mock recorder for MockBalanceGetter.
type MockBalanceGetterMockRecorder struct {
	mock *MockBalanceGetter
}

// NewMockBalanceGetter creates a new mock instance.
func NewMockBalanceGetter(ctrl *gomock.Controller) *MockBalanceGetter {
	mock := &MockBalanceGetter{ctrl: ctrl}
	mock.recorder = &MockBalanceGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceGetter) EXPECT() *MockBalanceGetterMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockBalanceGetter) Execute(ctx context.Context, userID string) (*domain.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, userID)
	ret0, _ := ret[0].(*domain.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockBalanceGetterMockRecorder) Execute(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockBalanceGetter)(nil).Execute), ctx, userID)
}
